### ISSUE TITLE
依頼】

### ISSUE THREAD

**Issue by naoyatsuchida** [naoyatsuchida/chat-space#15]

**Comment by naoyatsuchida** [comment]
#ip アドレス
13.113.249.28

**Comment by yasunamiura** [comment]
土田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**①背景をサイドバーと同じ紺色にしましょう
②グループ名と新着メッセージの下線をなくしましょう**
<img width="624" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/76722210-f8297800-6785-11ea-8cc9-c39718fab202.png">
見本
<img width="288" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/76722231-0e373880-6786-11ea-8287-ae2275f93008.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naoyatsuchida** [comment]
#viewの訂正
修正しました

**Comment by yasunamiura** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、前回と同じ不備が見受けられましたので修正をお願いします！

**※もう一度デプロイをしていただき本番環境に反映されているか確認をお願いします！**

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、前回と同じ不備が見受けられましたので修正をお願いします。
<img width="1440" alt="スクリーンショット 2020-03-17 10 46 18" src="https://user-images.githubusercontent.com/49669977/76813858-9710ab80-683c-11ea-94e8-a104b5b8ae30.png">

マージを忘れている、デプロイがうまくっていないなどはありませんか？
もし技術的な質問をされたい場合は、テックコネクトへお願いいたします！

本番環境にて修正が確認出来次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naoyatsuchida** [comment]
#申し訳ございません本番環境でも確認ができました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項はしっかり修正できていました！

新たに以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・サイドバーに表示されるグループの最新メッセージが規定よりも小さく、文字が読めない
<見本>
<img width="571" alt="スクリーンショット 2020-03-17 12 58 44" src="https://user-images.githubusercontent.com/49669977/76820629-160edf80-684f-11ea-9920-5247215c956d.png">

参照カリキュラム
https://master.tech-camp.in/curriculums/3944

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naoyatsuchida** [comment]
#修正しました

**Comment by naru6117** [comment]
修正とご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
